In [1]:
# ============================================================
# Import Required Libraries
# ============================================================

import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore warning messages to keep output clean
import warnings
warnings.filterwarnings("ignore")

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
# ============================================================
# Load the Seoul Bike Sharing Dataset
# ============================================================

# Load the dataset
df = pd.read_csv("SeoulBikeData.csv", encoding="latin1")

# Display first five rows
df.head()

,Date,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [3]:
# ============================================================
#  Checking Dataset Shape and Column Names
# ============================================================

# Check number of rows and columns
print("Dataset shape:", df.shape)

# Display all column names
print("\nColumn names:")
print(df.columns.tolist())

Dataset shape: (8760, 14)

Column names:
['Date', 'Rented Bike Count', 'Hour', 'Temperature(°C)', 'Humidity(%)', 'Wind speed (m/s)', 'Visibility (10m)', 'Dew point temperature(°C)', 'Solar Radiation (MJ/m2)', 'Rainfall(mm)', 'Snowfall (cm)', 'Seasons', 'Holiday', 'Functioning Day']

In [4]:
# ============================================================
#  Check Dataset Information
# ============================================================

# Display data types and non-null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       8760 non-null   object
 1   Rented Bike Count          8760 non-null   int64
 2   Hour                       8760 non-null   int64
 3   Temperature(°C)            8760 non-null   float64
 4   Humidity(%)                8760 non-null   int64
 5   Wind speed (m/s)           8760 non-null   float64
 6   Visibility (10m)           8760 non-null   int64
 7   Dew point temperature(°C)  8760 non-null   float64
 8   Solar Radiation (MJ/m2)    8760 non-null   float64
 9   Rainfall(mm)               8760 non-null   float64
 10  Snowfall (cm)              8760 non-null   float64
 11  Seasons                    8760 non-null   object
 12  Holiday                    8760 non-null   object
 13  Functioning Day            8760 non-null   object
dtypes: float64(6), int64(4), object(4)
memory usage: 958.3+ KB

In [5]:
# ============================================================
#   Summary Statistics of Numerical Columns
# ============================================================

# Show statistical summary
df.describe()

,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm)
count,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000
mean,704.602055,11.500000,12.882922,58.226256,1.724909,1436.825799,4.073813,0.569111,0.148687,0.075068
std,644.997468,6.922582,11.944825,20.362413,1.036300,608.298712,13.060369,0.868746,1.128193,0.436746
min,0.000000,0.000000,-17.800000,0.000000,0.000000,27.000000,-30.600000,0.000000,0.000000,0.000000
25%,191.000000,5.750000,3.500000,42.000000,0.900000,940.000000,-4.700000,0.000000,0.000000,0.000000
50%,504.500000,11.500000,13.700000,57.000000,1.500000,1698.000000,5.100000,0.010000,0.000000,0.000000
75%,1065.250000,17.250000,22.500000,74.000000,2.300000,2000.000000,14.800000,0.930000,0.000000,0.000000
max,3556.000000,23.000000,39.400000,98.000000,7.400000,2000.000000,27.200000,3.520000,35.000000,8.800000

In [6]:
# ============================================================
#   Clean Column Names
# ============================================================

# Removing extra spaces and replace spaces/symbols with underscores
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("(", "", regex=False)
df.columns = df.columns.str.replace(")", "", regex=False)
df.columns = df.columns.str.replace("/", "_", regex=False)

# Displaying updated column names
print("Cleaned column names:")
print(df.columns.tolist())

Cleaned column names:
['Date', 'Rented_Bike_Count', 'Hour', 'Temperature°C', 'Humidity%', 'Wind_speed_m_s', 'Visibility_10m', 'Dew_point_temperature°C', 'Solar_Radiation_MJ_m2', 'Rainfallmm', 'Snowfall_cm', 'Seasons', 'Holiday', 'Functioning_Day']

In [7]:
# ============================================================
#  Check Missing Values
# ============================================================

# Count missing values in each column
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Date                       0
Rented_Bike_Count          0
Hour                       0
Temperature°C              0
Humidity%                  0
Wind_speed_m_s             0
Visibility_10m             0
Dew_point_temperature°C    0
Solar_Radiation_MJ_m2      0
Rainfallmm                 0
Snowfall_cm                0
Seasons                    0
Holiday                    0
Functioning_Day            0
dtype: int64

In [8]:
# ============================================================
#   Check Duplicate Rows
# ============================================================

# Count duplicate rows
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [9]:
# ============================================================
#   9: Remove Duplicate Rows
# ============================================================

# Remove duplicate rows if present
df = df.drop_duplicates()

# Check new dataset shape
print("Dataset shape after removing duplicates:", df.shape)

Dataset shape after removing duplicates: (8760, 14)

In [10]:
# ============================================================
#  Identify Categorical Columns
# ============================================================

# Select columns with object datatype
categorical_columns = df.select_dtypes(include=["object"]).columns

# Display categorical columns
print("Categorical columns:")
print(categorical_columns.tolist())

Categorical columns:
['Date', 'Seasons', 'Holiday', 'Functioning_Day']

In [11]:
# ============================================================
#  Check Unique Values in Categorical Columns
# ============================================================

# Display unique values in each categorical column
for col in categorical_columns:
    print(f"\nUnique values in {col}:")
    print(df[col].unique())

Unique values in Date:
['01/12/2017' '02/12/2017' '03/12/2017' '04/12/2017' '05/12/2017'
 '06/12/2017' '07/12/2017' '08/12/2017' '09/12/2017' '10/12/2017'
 '11/12/2017' '12/12/2017' '13/12/2017' '14/12/2017' '15/12/2017'
 '16/12/2017' '17/12/2017' '18/12/2017' '19/12/2017' '20/12/2017'
 '21/12/2017' '22/12/2017' '23/12/2017' '24/12/2017' '25/12/2017'
 '26/12/2017' '27/12/2017' '28/12/2017' '29/12/2017' '30/12/2017'
 '31/12/2017' '01/01/2018' '02/01/2018' '03/01/2018' '04/01/2018'
 '05/01/2018' '06/01/2018' '07/01/2018' '08/01/2018' '09/01/2018'
 '10/01/2018' '11/01/2018' '12/01/2018' '13/01/2018' '14/01/2018'
 '15/01/2018' '16/01/2018' '17/01/2018' '18/01/2018' '19/01/2018'
 '20/01/2018' '21/01/2018' '22/01/2018' '23/01/2018' '24/01/2018'
 '25/01/2018' '26/01/2018' '27/01/2018' '28/01/2018' '29/01/2018'
 '30/01/2018' '31/01/2018' '01/02/2018' '02/02/2018' '03/02/2018'
 '04/02/2018' '05/02/2018' '06/02/2018' '07/02/2018' '08/02/2018'
 '09/02/2018' '10/02/2018' '11/02/2018' '12/02/2018' '13/02/2018'
 '14/02/2018' '15/02/2018' '16/02/2018' '17/02/2018' '18/02/2018'
 '19/02/2018' '20/02/2018' '21/02/2018' '22/02/2018' '23/02/2018'
 '24/02/2018' '25/02/2018' '26/02/2018' '27/02/2018' '28/02/2018'
 '01/03/2018' '02/03/2018' '03/03/2018' '04/03/2018' '05/03/2018'
 '06/03/2018' '07/03/2018' '08/03/2018' '09/03/2018' '10/03/2018'
 '11/03/2018' '12/03/2018' '13/03/2018' '14/03/2018' '15/03/2018'
 '16/03/2018' '17/03/2018' '18/03/2018' '19/03/2018' '20/03/2018'
 '21/03/2018' '22/03/2018' '23/03/2018' '24/03/2018' '25/03/2018'
 '26/03/2018' '27/03/2018' '28/03/2018' '29/03/2018' '30/03/2018'
 '31/03/2018' '01/04/2018' '02/04/2018' '03/04/2018' '04/04/2018'
 '05/04/2018' '06/04/2018' '07/04/2018' '08/04/2018' '09/04/2018'
 '10/04/2018' '11/04/2018' '12/04/2018' '13/04/2018' '14/04/2018'
 '15/04/2018' '16/04/2018' '17/04/2018' '18/04/2018' '19/04/2018'
 '20/04/2018' '21/04/2018' '22/04/2018' '23/04/2018' '24/04/2018'
 '25/04/2018' '26/04/2018' '27/04/2018' '28/04/2018' '29/04/2018'
 '30/04/2018' '01/05/2018' '02/05/2018' '03/05/2018' '04/05/2018'
 '05/05/2018' '06/05/2018' '07/05/2018' '08/05/2018' '09/05/2018'
 '10/05/2018' '11/05/2018' '12/05/2018' '13/05/2018' '14/05/2018'
 '15/05/2018' '16/05/2018' '17/05/2018' '18/05/2018' '19/05/2018'
 '20/05/2018' '21/05/2018' '22/05/2018' '23/05/2018' '24/05/2018'
 '25/05/2018' '26/05/2018' '27/05/2018' '28/05/2018' '29/05/2018'
 '30/05/2018' '31/05/2018' '01/06/2018' '02/06/2018' '03/06/2018'
 '04/06/2018' '05/06/2018' '06/06/2018' '07/06/2018' '08/06/2018'
 '09/06/2018' '10/06/2018' '11/06/2018' '12/06/2018' '13/06/2018'
 '14/06/2018' '15/06/2018' '16/06/2018' '17/06/2018' '18/06/2018'
 '19/06/2018' '20/06/2018' '21/06/2018' '22/06/2018' '23/06/2018'
 '24/06/2018' '25/06/2018' '26/06/2018' '27/06/2018' '28/06/2018'
 '29/06/2018' '30/06/2018' '01/07/2018' '02/07/2018' '03/07/2018'
 '04/07/2018' '05/07/2018' '06/07/2018' '07/07/2018' '08/07/2018'
 '09/07/2018' '10/07/2018' '11/07/2018' '12/07/2018' '13/07/2018'
 '14/07/2018' '15/07/2018' '16/07/2018' '17/07/2018' '18/07/2018'
 '19/07/2018' '20/07/2018' '21/07/2018' '22/07/2018' '23/07/2018'
 '24/07/2018' '25/07/2018' '26/07/2018' '27/07/2018' '28/07/2018'
 '29/07/2018' '30/07/2018' '31/07/2018' '01/08/2018' '02/08/2018'
 '03/08/2018' '04/08/2018' '05/08/2018' '06/08/2018' '07/08/2018'
 '08/08/2018' '09/08/2018' '10/08/2018' '11/08/2018' '12/08/2018'
 '13/08/2018' '14/08/2018' '15/08/2018' '16/08/2018' '17/08/2018'
 '18/08/2018' '19/08/2018' '20/08/2018' '21/08/2018' '22/08/2018'
 '23/08/2018' '24/08/2018' '25/08/2018' '26/08/2018' '27/08/2018'
 '28/08/2018' '29/08/2018' '30/08/2018' '31/08/2018' '01/09/2018'
 '02/09/2018' '03/09/2018' '04/09/2018' '05/09/2018' '06/09/2018'
 '07/09/2018' '08/09/2018' '09/09/2018' '10/09/2018' '11/09/2018'
 '12/09/2018' '13/09/2018' '14/09/2018' '15/09/2018' '16/09/2018'
 '17/09/2018' '18/09/2018' '19/09/2018' '20/09/2018' '21/09/2018'
 '22/09/2018' '23/09/2018' '24/09/2018' '25/09/2018' '26/09/2018'
 '27/09/2018' '28/09/2018' '29/09/2018' '30/09/2018' '01/10/2018'
 '02/10/2018' '03/10/2018' '04/10/2018' '05/10/2018' '06/10/2018'
 '07/10/2018' '08/10/2018' '09/10/2018' '10/10/2018' '11/10/2018'
 '12/10/2018' '13/10/2018' '14/10/2018' '15/10/2018' '16/10/2018'
 '17/10/2018' '18/10/2018' '19/10/2018' '20/10/2018' '21/10/2018'
 '22/10/2018' '23/10/2018' '24/10/2018' '25/10/2018' '26/10/2018'
 '27/10/2018' '28/10/2018' '29/10/2018' '30/10/2018' '31/10/2018'
 '01/11/2018' '02/11/2018' '03/11/2018' '04/11/2018' '05/11/2018'
 '06/11/2018' '07/11/2018' '08/11/2018' '09/11/2018' '10/11/2018'
 '11/11/2018' '12/11/2018' '13/11/2018' '14/11/2018' '15/11/2018'
 '16/11/2018' '17/11/2018' '18/11/2018' '19/11/2018' '20/11/2018'
 '21/11/2018' '22/11/2018' '23/11/2018' '24/11/2018' '25/11/2018'
 '26/11/2018' '27/11/2018' '28/11/2018' '29/11/2018' '30/11/2018']

Unique values in Seasons:
['Winter' 'Spring' 'Summer' 'Autumn']

Unique values in Holiday:
['No Holiday' 'Holiday']

Unique values in Functioning_Day:
['Yes' 'No']

In [12]:
# ============================================================
# Convert Date Column to Datetime Format
# ============================================================

# Convert Date column from object/text format into datetime format
df["Date"] = pd.to_datetime(df["Date"], format="%d/%m/%Y")

# Check the updated datatype of Date column
print("Date column datatype after conversion:")
print(df["Date"].dtype)

# Display first five date values
df["Date"].head()

Date column datatype after conversion:
datetime64[ns]

0   2017-12-01
1   2017-12-01
2   2017-12-01
3   2017-12-01
4   2017-12-01
Name: Date, dtype: datetime64[ns]

In [13]:
# ============================================================
#  Create New Date-Based Features
# ============================================================

# Extract day from Date
df["Day"] = df["Date"].dt.day

# Extract month from Date
df["Month"] = df["Date"].dt.month

# Extract weekday from Date
# Monday = 0, Tuesday = 1, ..., Sunday = 6
df["Weekday"] = df["Date"].dt.weekday

# Display the new date-based features
df[["Date", "Day", "Month", "Weekday"]].head()

        Date  Day  Month  Weekday
0 2017-12-01    1     12        4
1 2017-12-01    1     12        4
2 2017-12-01    1     12        4
3 2017-12-01    1     12        4
4 2017-12-01    1     12        4

In [14]:
# ============================================================
#  Drop Original Date Column
# ============================================================

# Drop the original Date column because useful features are already extracted
df = df.drop("Date", axis=1)

# Display updated columns
print("Columns after dropping Date:")
print(df.columns.tolist())

Columns after dropping Date:
['Rented_Bike_Count', 'Hour', 'Temperature°C', 'Humidity%', 'Wind_speed_m_s', 'Visibility_10m', 'Dew_point_temperature°C', 'Solar_Radiation_MJ_m2', 'Rainfallmm', 'Snowfall_cm', 'Seasons', 'Holiday', 'Functioning_Day', 'Day', 'Month', 'Weekday']

In [15]:
# ============================================================
# Check Remaining Categorical Columns
# ============================================================

# Check remaining categorical columns after dropping Date
categorical_columns = df.select_dtypes(include=["object"]).columns

print("Remaining categorical columns:")
print(categorical_columns.tolist())

Remaining categorical columns:
['Seasons', 'Holiday', 'Functioning_Day']

In [16]:
# ============================================================
# Encode Categorical Variables
# ============================================================

# Convert categorical variables into numerical format
df = pd.get_dummies(
    df,
    columns=["Seasons", "Holiday", "Functioning_Day"],
    drop_first=True
)

# Displaying first five rows
df.head()

,Rented_Bike_Count,Hour,Temperature°C,Humidity%,Wind_speed_m_s,Visibility_10m,Dew_point_temperature°C,Solar_Radiation_MJ_m2,Rainfallmm,Snowfall_cm,Day,Month,Weekday,Seasons_Spring,Seasons_Summer,Seasons_Winter,Holiday_No Holiday,Functioning_Day_Yes
0,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,1,12,4,False,False,True,True,True
1,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,1,12,4,False,False,True,True,True
2,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,1,12,4,False,False,True,True,True
3,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,1,12,4,False,False,True,True,True
4,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,1,12,4,False,False,True,True,True

In [17]:
# ============================================================
# Convert Boolean Columns to Integer
# ============================================================

# Convert boolean columns into integer values 0 and 1
bool_columns = df.select_dtypes(include=["bool"]).columns

df[bool_columns] = df[bool_columns].astype(int)

print("Boolean columns converted to integers:")
print(bool_columns.tolist())

# Displaying first five rows
df.head()

Boolean columns converted to integers:
['Seasons_Spring', 'Seasons_Summer', 'Seasons_Winter', 'Holiday_No Holiday', 'Functioning_Day_Yes']

,Rented_Bike_Count,Hour,Temperature°C,Humidity%,Wind_speed_m_s,Visibility_10m,Dew_point_temperature°C,Solar_Radiation_MJ_m2,Rainfallmm,Snowfall_cm,Day,Month,Weekday,Seasons_Spring,Seasons_Summer,Seasons_Winter,Holiday_No Holiday,Functioning_Day_Yes
0,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,1,12,4,0,0,1,1,1
1,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,1,12,4,0,0,1,1,1
2,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,1,12,4,0,0,1,1,1
3,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,1,12,4,0,0,1,1,1
4,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,1,12,4,0,0,1,1,1

In [18]:
# ============================================================
# Final Dataset Information After Encoding
# ============================================================

# Checking final dataset shape
print("Final dataset shape:", df.shape)

# final data types
df.info()

Final dataset shape: (8760, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rented_Bike_Count        8760 non-null   int64
 1   Hour                     8760 non-null   int64
 2   Temperature°C            8760 non-null   float64
 3   Humidity%                8760 non-null   int64
 4   Wind_speed_m_s           8760 non-null   float64
 5   Visibility_10m           8760 non-null   int64
 6   Dew_point_temperature°C  8760 non-null   float64
 7   Solar_Radiation_MJ_m2    8760 non-null   float64
 8   Rainfallmm               8760 non-null   float64
 9   Snowfall_cm              8760 non-null   float64
 10  Day                      8760 non-null   int32
 11  Month                    8760 non-null   int32
 12  Weekday                  8760 non-null   int32
 13  Seasons_Spring           8760 non-null   int64
 14  Seasons_Summer           8760 non-null   int64
 15  Seasons_Winter           8760 non-null   int64
 16  Holiday_No Holiday       8760 non-null   int64
 17  Functioning_Day_Yes      8760 non-null   int64
dtypes: float64(6), int32(3), int64(9)
memory usage: 1.1 MB

In [19]:
# ============================================================
# Final Missing Value Check
# ============================================================

# Checking missing values after preprocessing
print("Final missing values:")
print(df.isnull().sum())

Final missing values:
Rented_Bike_Count          0
Hour                       0
Temperature°C              0
Humidity%                  0
Wind_speed_m_s             0
Visibility_10m             0
Dew_point_temperature°C    0
Solar_Radiation_MJ_m2      0
Rainfallmm                 0
Snowfall_cm                0
Day                        0
Month                      0
Weekday                    0
Seasons_Spring             0
Seasons_Summer             0
Seasons_Winter             0
Holiday_No Holiday         0
Functioning_Day_Yes        0
dtype: int64

In [20]:
# ============================================================
# Separate Features and Target Variable
# ============================================================

# Defining target variable
target = "Rented_Bike_Count"

# X contains independent/input features
X = df.drop(target, axis=1)

# y contains dependent/target variable
y = df[target]

print("Feature dataset shape:", X.shape)
print("Target dataset shape:", y.shape)

Feature dataset shape: (8760, 17)
Target dataset shape: (8760,)

In [21]:
# ============================================================
#Preprocessed Dataset
# ============================================================

df.to_csv("preprocessed_seoul_bike_data.csv", index=False)

print("Preprocessed dataset saved successfully.")

Preprocessed dataset saved successfully.

In [22]:
# ============================================================
# Downloading the Preprocessed Dataset
# ============================================================

from google.colab import files

files.download("preprocessed_seoul_bike_data.csv")